import {
  EXPO_CLOUDINARY_API_KEY,
  EXPO_CLOUDINARY_API_SECRET,
  EXPO_CLOUDINARY_CLOUD_NAME,
  EXPO_CLOUDINARY_UPLOAD_PRESET,
} from "@env";

export const CLOUDINARY_CLOUD_NAME = EXPO_CLOUDINARY_CLOUD_NAME;
export const CLOUDINARY_UPLOAD_PRESET = EXPO_CLOUDINARY_UPLOAD_PRESET;
export const CLOUDINARY_API_KEY = EXPO_CLOUDINARY_API_KEY;
export const CLOUDINARY_API_SECRET = EXPO_CLOUDINARY_API_SECRET;
